def handle(event, context):
    print('Task finished with failure!')
